export const fullMenu = [
    { section: "Aperitivos", name: "CHIPS & SALSA", description: "2 homemade salsas, verde / roja", price: 8 },
    { section: "Aperitivos", name: "ORO VERDE", description: "avocado, onion, lime, jalapeño, cilantro", price: 15 },
    { section: "Aperitivos", name: "QUESO FUNDIDO", description: "baked chihuahua cheese", price: 15, options: [{ name: "chorizo", price: 4 }, { name: "poblano peppers", price: 3 }] },
    { section: "Aperitivos", name: "QUESO EN LLAMAS", description: "flamed tableside panela cheese", price: 15 },
    { section: "Aperitivos", name: "FLAUTAS", description: "4 crispy tortillas, sour cream, cotija, and cabbage. Stuffed with your choice of chicken or potatoes", price: 18 },
    { section: "Aperitivos", name: "*LAS MOMIAS", description: "4 bacon wrapped jumbo shrimp, stuffed with spinach jalapeño cream cheese, aioli", price: 22, cookedToOrder: true },
    { section: "Aperitivos", name: "QUESADILLAS", description: "chihuaha and oaxaca cheese, poblano peppers, crema, pico de gallo", price: 14, options: [{ name: "carne", price: 6 }, { name: "pollo", price: 4 }] },
    { section: "Aperitivos", name: "CHILITOS", description: "4 grilled stuffed jalapeños with creme cheese, spinach, and bacon", price: 14 },
    { section: "Mariscos", name: "FRIED or GRILLED CALAMARI", description: "golden fried, homemade spicy cocktail sauce", price: 18 },
    { section: "Mariscos", name: "FRIED or GRILLED SHRIMP", description: "four jumbo tiger shrimp, homemade spicy cocktail sauce", price: 22 },
    { section: "Mariscos", name: "*CEVICHAZO", description: "traditional homemade shrimp ceviche", price: 22, cookedToOrder: true },
    { section: "Mariscos", name: "*AGUACHILES", description: "mexican dish made of shrimp, seasoned with chiltepin peppers, lime juice, cucumber, and slices of onion", price: 22, cookedToOrder: true },
    { section: "Mariscos", name: "BUTTER LIME SHRIMP", description: "6 grilled shrimp, parsley, garlic, and our butter lime sauce", price: 22 },
    { section: "Mariscos", name: "*OYSTERS ROCKERFELLER", description: "4 pcs topped with a rich homemade sauce and spinach", price: 18, cookedToOrder: true },
    { section: "Mariscos", name: "*OYSTERS", description: "west or east coast, homemade cocktail sauce, mignonette, and lemon", options: [{ quantity: 6, price: 19 }, { quantity: 12, price: 33 }], cookedToOrder: true },
    { section: "Ensaladas", name: "EL CAESAR", description: "romaine lettuce, parmesan cheese, croutons, Caesar dressing", price: 15 },
    { section: "Ensaladas", name: "BOCADITOS MIX", description: "spring mix, green apples, panela cheese, pecans, dried cranberries, chopped bacon, balsamic vinaigrette", price: 16 },
    { section: "Ensaladas", name: "ADD PROTEIN", description: "Enhance your salad with your choice of protein", options: [{ name: "chicken", price: 5, cookedToOrder: true }, { name: "steak", price: 10, cookedToOrder: true }, { name: "shrimp", price: 7 }, { name: "salmon", price: 10, cookedToOrder: true }] },
    { section: "Kids", name: "2 TACOS", description: "steak or pollo", price: 10 },
    { section: "Kids", name: "MINI QUESADILLAS", description: "steak or pollo", price: 10 },
    { section: "Tacos", name: "*CARNE", description: "marinated skirt steak, crispy shallots, salsa verde", price: 18, cookedToOrder: true },
    { section: "Tacos", name: "*POLLO", description: "grilled chicken marinated with homemade ranchero sauce, topped with cabbage mix", price: 16, cookedToOrder: true },
    { section: "Tacos", name: "COCHINITA PIBIL", description: "pork rubbed with achiote and citrus, slowly smoke-roasted. topped with pickled onion and habanero", price: 16 },
    { section: "Tacos", name: "CAMARON", description: "grilled shrimp marinated with guajillo sauce, topped with avocado and cilantro", price: 18 },
    { section: "Tacos", name: "ESTILO BAJA", description: "grilled or fried tilapia, topped with cabbage and chipotle aioli", price: 18 },
    { section: "Tacos", name: "VEGETALES", description: "sautéed green peppers, potatoes, and onion", price: 15 },
    { section: "Algo Más", name: "MASHED POTATOES", price: 10 },
    { section: "Algo Más", name: "ASPARAGUS", price: 10 },
    { section: "Algo Más", name: "SAUTEED SPINACH", price: 10 },
    { section: "Algo Más", name: "FRENCH FRIES", price: 8 },
    { section: "Algo Más", name: "ELOTE", description: "mayo, cotija, chili piquin", price: 10 },
    { section: "Algo Más", name: "MAC AND CHEESE", description: "everyone’s cheesy favorite", price: 15 },
    { section: "Algo Más", name: "SPANISH RICE", price: 3 },
    { section: "Algo Más", name: "REFRIED BEANS", price: 3 },
    { section: "Entradas", name: "*DON RIBEYE", description: "12oz ribeye, mashed potatoes, asparagus", price: 49, cookedToOrder: true },
    { section: "Entradas", name: "*HAWAIIAN RIBEYE", description: "12oz ribeye homemade marinated", price: 39, cookedToOrder: true },
    { section: "Entradas", name: "*MAR Y TIERRA", description: "filet mignon, jumbo tiger shrimp, mashed potato", price: 55, cookedToOrder: true },
    { section: "Entradas", name: "*TAMPIQUEÑA", description: "marinated skirt steak, mexican rice, mole enchilada", price: 30, cookedToOrder: true },
    { section: "Entradas", name: "*FAJITAS", description: "sizzling platter of caramelized onion, roasted green and red peppers, and zucchini", options: [{ name: "chicken", price: 27 }, { name: "steak", price: 30 }, { name: "add shrimp", price: 7 }], cookedToOrder: true },
    { section: "Entradas", name: "*SALMON AZTECA", description: "homemade marinated salmon, parsnip puree, asparagus, fried potato ring", price: 28, cookedToOrder: true },
    { section: "Entradas", name: "POLLO TOTONIL", description: "roasted chicken, yellow and green zucchini, mashed potatoes", price: 26 },
    { section: "Entradas", name: "ENCHILADAS MAYA", description: "roasted chicken, sour cream, cotija, lettuce, avocado, choice of verde or mole sauce", price: 24 },
    { section: "Entradas", name: "PASTA POBLANA", description: "fettuccini pasta, poblanos, jalapeno, cheese", price: 20, options: [{ name: "add grilled pollo", price: 5 }, { name: "add grilled shrimp", price: 8 }] },
    { section: "Entradas", name: "*OAXACA BURGER", description: "8oz ground beef, brioche bun, oaxaca and chihuaha cheese, arugula, guacamole, jalapenos, side of fries", price: 18, cookedToOrder: true },
    { section: "Entradas", name: "TRUFFLE LOBSTER MAC AND CHEESE", price: 25 },
  ];
  